# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c85e8bca8afebe69c707bf4d4b6a4e221de084df604b4a8b73765fa27933a410854f526b4988e2cb5be052963cfe39dad327f1b8c54e68e5285c47fb4df6b219

test:
  secret_key_base: accfe9d99a8dc452612e2b476503bf1070c62ea70cf57d9f55e3c885b729275dff0ec26bbae51835d20c20d8e5f564fc8c7aa37fa325f8fcedbdb6847a08a60e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
